default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  #  host: db
  # ↓↓CiecleCI に通すときはコメントアウト
#  password: <%#= ENV['MYSQL_ROOT_PASSWORD'] || '' %>

development:
  <<: *default
  database: app_development
  
test:
  <<: *default
  database: app_test
  # ↓↓CiecleCI に通すときはコメントイン
  host: 127.0.0.1

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
#  url: terraform-20221023041629708800000006.cbch251i7aoz.ap-northeast-1.rds.amazonaws.com
  database: production
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>

  