default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  host: db
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] || '' %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  adapter: mysql2
  database: production
  username: <%= ENV['DATABASE_USER'] %>
  url: <%= ENV['DATABASE_URL'] %>
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
