default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  host: db
  # ↓↓CiecleCI に通すときはコメントアウト
  # password: <%= ENV['MYSQL_ROOT_PASSWORD'] || '' %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test
  # ↓↓CiecleCI に通すときはコメントイン
  host: 127.0.0.1

production:
  <<: *default
  #  url: <%= ENV['RDS_ENDPOINT'] %>
  url: terraform-20230125021324605800000001.cbch251i7aoz.ap-northeast-1.rds.amazonaws.com
  username: kento
  database: production
  # Just a test. It shouldn't be used in production.
  password: 8EsZDP9TYgHdUUM7C2N7Qqeici2ReTfNtBeQ
