default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  host: db
  # ↓↓CiecleCI に通すときはコメントアウト
  # password: <%= ENV['DATABASE_PASSWORD'] || '' %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: production
  password: <%= ENV['DATABASE_PASSWORD'] %>
  # Just a test. It shouldn't be used in production.
