default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  host: db
  # ↓↓CiecleCI に通すときはコメントアウト
  # password: <%= ENV['DATABASE_PASSWORD'] || '' %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] || 'terraform-20230311014306944900000001.cbch251i7aoz.ap-northeast-1.rds.amazonaws.com' %>
  database: production
  password: <%= ENV['DATABASE_PASSWORD'] || '8EsZDP9TYgHdUUM7C2N7Qqeici2ReTfNtBeQ' %>
  # Just a test. It shouldn't be used in production.
