default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  host: db
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] || '' %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  adapter: mysql2
  database: production
  username: kento
  url: terraform-20230218010631604700000001.cbch251i7aoz.ap-northeast-1.rds.amazonaws.com
  password: 8EsZDP9TYgHdUUM7C2N7Qqeici2ReTfNtBeQ
  # Just a test. It shouldn't be used in production.
