version: "3.7"

services:
  mwk-db:
    image: mysql:8.0
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: $MYSQL_ALLOW_EMPTY_PASSWORD
    restart: always
    volumes:
      - /var/lib/docker/volumes/mwk-db-data:/var/lib/mysql:cached

  backend:
    build:
      context: ./backend
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
    #    container_name: backend
    #    build: ./backend/
    #    image: backend
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_ALLOW_EMPTY_PASSWORD: $MYSQL_ALLOW_EMPTY_PASSWORD
      API_DOMAIN: "localhost:$FRONT_PORT"
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - 5001:3000
    #      - "$API_PORT:$CONTAINER_PORT"
    volumes:
      - ./backend:/$WORKDIR:cached
      - bundle_data:/usr/local/bundle:cached
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
  #    networks:
  #      app_net:
  #        ipv4_address: '172.21.0.3'

  mwk-frontend:
    build:
      context: ./frontend
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
        API_URL: "http://localhost:$API_PORT"
    command: npm run dev
    container_name: mwk-frontend
    #    build: ./frontend/
    #    image: frontend
    volumes:
      - node_modules_volume:/$WORKDIR/node_modules
      - /home/user/app/frontend:/app:cached
      - /var/lib/docker/volumes/mwk-node-modules/_data:/app/node_modules
    # node_modulesはホストと共有しないでvolumeマウント
    ports:
      - 3000:80
    #    - "$FRONT_PORT:$CONTAINER_PORT"
    #    networks:
    #      app_net:
    #        ipv4_address: '172.21.0.4'
    depends_on:
      - backend

#networks:
#  app_net:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.21.0.0/24

volumes:
  mwk-db-data:
  mwk-bundle-cache:
  mwk-node-modules:
  bundle_data:
  rails-cache:
  yarn_cache:
