---
name: Build & Deploy to Amazon ECS

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'

jobs:
  deploy:
    name: Deploy
    strategy:
      matrix:
        ruby: ["2.7.1"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    environment: production
    permissions:
      id-token: write
      contents: read
      actions: read

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/iam_role_for_github_actions
          role-session-name: iam_role_for_github_actions

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.4.0

      - name: Build and push
        uses: docker/build-push-action@v3
        env:
          ARG_RUBY_VERSION: ${{ matrix.ruby }}
          AWS_ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
          AWS_ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
        with:
          context: .
          push: true
          build-args: |
            ARG_RUBY_VERSION=${{ matrix.ruby }}
          tags: $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

#      - name: Build app and push image to AWS ECR
#        env:
#          ARG_RUBY_VERSION: ${{ matrix.ruby }}
#          AWS_ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
#          AWS_ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
#        run: |
#               IMAGE_TAG=${{ github.sha }}
#               docker build -t $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:$IMAGE_TAG -f ./backend/Dockerfile.prd ./backend --build-arg ARG_RUBY_VERSION=${{ matrix.ruby }}
#               docker push $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:$IMAGE_TAG
#               echo "::set-output name=image::${AWS_ECR_REGISTRY}/${AWS_ECR_REPOSITORY}:${IMAGE_TAG}"

#         IMAGE_TAG=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
#          AWS_ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs/prj-name_backend_definition.json
          container-name: mwk-backend
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ secrets.AWS_ECS_SERVICE }}
          cluster: ${{ secrets.AWS_ECS_CLUSTER }}
